import streamlit as st
from streamlit_drawable_canvas import st_canvas
import numpy as np
import pickle
import cv2
import os
import pandas as pd

# --- 1. MODEL LOADING ---
@st.cache_resource
def load_model():
    # Loading the trained weights generated by your training script
    with open('models/digits_model.pkl', 'rb') as f:
        return pickle.load(f)

model = load_model()

# --- 2. HELPER FUNCTIONS ---
def softmax(S):
    exps = np.exp(S - np.max(S))
    return exps / np.sum(exps)

def predict(X):
    # Forward pass: Input -> Hidden (tanh) -> Output -> Softmax
    Z1 = X @ model['W1'].T + model['b1'].T
    H = np.tanh(Z1)
    S = H @ model['W2'].T + model['b2'].T
    return softmax(S)

# --- 3. UI CONFIGURATION ---
st.set_page_config(page_title="UFAZ AI Project", layout="wide")
st.sidebar.title("🚀 Navigation")
page = st.sidebar.radio("Go to:", 
    ["Digit Recognition Demo", "Model Performance Study", "Statistical Reliability", "Decision Boundaries"])

# --- PAGE 1: DIGIT RECOGNITION DEMO ---
if page == "Digit Recognition Demo":
    st.title("🔢 Handwritten Digit Recognition")
    st.write("Draw a digit (0-9) in the box below. The model will process it as an 8x8 image for classification.")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("Drawing Canvas")
        canvas_result = st_canvas(
            fill_color="rgba(255, 165, 0, 0.3)",
            stroke_width=18,
            stroke_color="#FFFFFF",
            background_color="#000000",
            height=280, width=280,
            drawing_mode="freedraw",
            key="canvas",
        )

    if canvas_result.image_data is not None:
        img = cv2.cvtColor(canvas_result.image_data.astype('uint8'), cv2.COLOR_RGBA2GRAY)
        if np.sum(img) > 0:
            # Preprocessing: Bounding box and scaling to 8x8
            coords = cv2.findNonZero(img)
            x, y, w, h = cv2.boundingRect(coords)
            rect_img = img[y:y+h, x:x+w]
            pad = 20
            size = max(w, h) + pad
            square_img = np.zeros((size, size), np.uint8)
            square_img[(size-h)//2:(size-h)//2+h, (size-w)//2:(size-w)//2+w] = rect_img
            
            img_resizing = cv2.resize(square_img, (8, 8), interpolation=cv2.INTER_AREA)
            img_resizing = cv2.normalize(img_resizing, None, 0, 255, cv2.NORM_MINMAX)
            # Normalizing to 0-16 range to match Scikit-learn's digits dataset format
            img_normalized = (img_resizing.flatten() / 255.0) * 16.0
            
            with col2:
                st.subheader("Model Perspective")
                probs = predict(img_normalized.reshape(1, -1))
                prediction = np.argmax(probs)
                confidence = np.max(probs)
                st.image(img_resizing, width=150, clamp=True, caption="Downsampled 8x8")
                st.metric("Prediction", f"{prediction}", f"{confidence*100:.2f}% Confidence")
            
            st.markdown("---")
            st.subheader("Probability Distribution")
            st.bar_chart(probs.flatten())
        else:
            st.info("Please draw a digit to start the prediction.")

# --- PAGE 2: MODEL PERFORMANCE STUDY ---
elif page == "Model Performance Study":
    st.title("📊 Optimizer Comparison")
    st.write("Results from the optimizer study conducted in `digit.py`.")
    
    # Using your actual test results
    data = {
        "Optimizer": ["SGD", "Momentum", "Adam"],
        "Test Accuracy": [0.9402, 0.9429, 0.9511]
    }
    df = pd.DataFrame(data)
    
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Final Test Accuracy")
        st.dataframe(df.style.highlight_max(subset=["Test Accuracy"], color='lightgreen'))
    
    with col2:
        st.subheader("Visual Comparison")
        st.bar_chart(df.set_index("Optimizer"))
    
    st.success(f"Adam outperformed other optimizers with an accuracy of {data['Test Accuracy'][2]*100:.2f}%.")

# --- PAGE 3: STATISTICAL RELIABILITY ---
elif page == "Statistical Reliability":
    st.title("🎲 Repeated Seeds Analysis")
    st.write("Evaluation of model stability across 5 different random seeds (1, 10, 42, 100, 2026).")
    
    st.metric("Mean Test Accuracy", "94.82%", "± 0.008 (95% CI)")
    
    st.info("""
    **Key Takeaway:** A single high-accuracy result might be due to luck in weight initialization. 
    Consistent performance across multiple seeds proves the robustness of the Adam optimizer architecture.
    """)

# --- PAGE 4: DECISION BOUNDARIES ---
# --- PAGE 4: DECISION BOUNDARIES ---
elif page == "Decision Boundaries":
    st.title("🌙 Moons Dataset: Boundary Visualization")
    st.write("Visualizing how increasing hidden layer complexity affects the non-linear classification boundary.")
    
    # Selection options
    option = st.selectbox("Select Hidden Dimension:", ["Softmax (Linear)", "2", "8", "32"])
    
    # Mapping selection to your exact file names seen in image_51fe85.png
    file_map = {
        "Softmax (Linear)": "moons_boundary_softmax.png",
        "2": "moons_boundary_2.png",
        "8": "moons_boundary_8.png",
        "32": "moons_boundary_32.png"
    }
    
    # Use Path to ensure the directory is found relative to app.py
    from pathlib import Path
    BASE_DIR = Path(__file__).resolve().parent
    img_path = BASE_DIR  / "figures" / file_map[option]
    
    if img_path.exists():
        st.image(str(img_path), caption=f"Boundary Visualization - Hidden Dim: {option}", use_container_width=True)
    else:
        st.error(f"File not found: {img_path}")
        st.write("Current Directory Content:", os.listdir(BASE_DIR / "figures") if (BASE_DIR / "figures").exists() else "Figures folder not found")